AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Template creates IAM role required to integrate Klarity with AWS CloudTrail Lake events.
Parameters:
  KlarityAccountId:
    Description: Klarity production Account ID
    Type: String
    MaxLength: 12
    MinLength: 12
    AllowedPattern: "^[0-9]*$"
    ConstraintDescription: Must be a 12 digit valid AWS Account ID
    Default: "855341727128"

  ExternalId:
    Description: Optional ExternalId required to assume KlarityCloudTrailIntegration
    Type: String
    MaxLength: 20
    MinLength: 10
    AllowedPattern: "^[0-9A-Za-z]*$"
    
Outputs:
  roleArn:
    Description: ARN of KlarityCloudTrailIntegration
    Value: !GetAtt KlarityCloudTrailIntegrationRole.Arn
Resources:
  KlarityCloudTrailIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: KlarityCloudTrailIntegration
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudtrail:CreateEventDataStore"
                  - "cloudtrail:UpdateEventDataStore"
                  - "cloudtrail:DeleteEventDataStore"
                  - "cloudtrail:ListEventDataStores"
                  - "cloudtrail:RestoreEventDataStore"
                  - "cloudtrail:GetEventDataStore"
                  - "cloudtrail:StartQuery"
                  - "cloudtrail:ListQueries"
                  - "cloudtrail:CancelQuery"
                  - "cloudtrail:DescribeQuery"
                  - "cloudtrail:GetQueryResults"
                  - "cloudtrail:CreateIngestionChannel"
                  - "cloudtrail:UpdateIngestionChannel"
                  - "cloudtrail:DeleteIngestionChannel"
                  - "cloudtrail:GetIngestionChannel"
                  - "cloudtrail:ListIngestionChannels"
                  - cloudtrail-data:PutAuditEvents
                  - iam:ListRoles
                  - iam:GetRolePolicy
                  - iam:GetUser
                Resource: "*"
              - Effect: Allow
                Action:
                  - "iam:PassRole"
                Resource: "*"
                Condition:
                  StringEquals:
                    "iam:PassedToService": "cloudtrail.amazonaws.com"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !Sub "arn:aws:iam::${KlarityAccountId}:root"
            Condition:
              StringEquals:
                "sts:ExternalId": !Sub "${ExternalId}"
